export type UploadFileParams = {
  /**
   * Raw binary data of the file.
   */
  data: Buffer | ArrayBuffer | Uint8Array;
  /**
   * MIME type supplied by the client.
   */
  contentType: string;
  /**
   * Original filename. Used only for naming metadata.
   */
  filename: string;
  /**
   * File size in bytes.
   */
  size: number;
};

export type UploadedFile = {
  /**
   * Unique identifier generated by the repository (e.g. blob name).
   */
  id: string;
  /**
   * MIME type stored alongside the object.
   */
  contentType: string;
  /**
   * File size in bytes.
   */
  size: number;
  /**
   * Optional opaque metadata from the provider (etag, version id, etc).
   */
  metadata?: Record<string, unknown>;
};

export interface ObjectStorageRepository {
  /**
   * Upload a file to the backing storage and return the created object metadata.
   */
  uploadFile(params: UploadFileParams): Promise<UploadedFile>;

  /**
   * Issue a temporary download URL (e.g. SAS) that clients can use directly.
   */
  getTemporaryDownloadUrl(
    objectId: string,
    options?: { expiresInSeconds?: number },
  ): Promise<string>;
}
